#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5433/bankcards_db}
    username: ${SPRING_DATASOURCE_USERNAME:bank_user}
    password: ${SPRING_DATASOURCE_PASSWORD:bank_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

jwt:
  secret: VGhpc0lzQVNlY3JldEtleUZvckp3dFRlc3RpbmdQdXJwb3Nlc09ubHkhMTIzNDU2
  expiration: 86400000

app:
  encryption:
    secret: MDEyMzQ1Njc4OWFiY2RlZg==
